stages:
  - build

variables:
  GO111MODULE: 'on'
  GOARCH: 'amd64'
  GOOS: 'linux'
  NODE_VERSION: '20'

services:
  - name: postgres:15-alpine
    alias: postgres

  - name: redis:7-alpine
    alias: redis

before_script:
  - apt-get update -qy
  - apt-get install -y curl gnupg2

  # Install Golang
  - curl -sSL https://golang.org/dl/go1.17.5.linux-amd64.tar.gz | tar -C /usr/local -xzf -
  - export PATH=$PATH:/usr/local/go/bin

  # Install Node.js
  - curl -sL https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash -
  - apt-get install -y nodejs

  # Install PNPM
  - npm install -g pnpm

build:
  stage: build
  script:
    - go mod download

    - pnpm install

    - pnpm run setup:go

    - pnpm run db-primary:migrate

    - pnpm run db-primary:seed
