version: '3.8'

services:
  caddy:
    image: caddy:<version>
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config

  postgres:
    container_name: checkpoint-db
    image: postgres:15-alpine
    environment:
      - POSTGRES_HOST=${PRIMARY_POSTGRES_SERVER_URL}
      - POSTGRES_DB=${PRIMARY_POSTGRES_DB_NAME}
      - POSTGRES_USER=${PRIMARY_POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${PRIMARY_POSTGRES_PASSWORD}
    ports:
      - ${PRIMARY_POSTGRES_SERVER_PORT}:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  redis:
    container_name: checkpoint-redis
    image: redis:7-alpine
    ports:
      - ${REDIS_SERVER_PORT}:6379
    command: --requirepass ${REDIS_PASSWORD}

  minio:
    image: quay.io/minio/minio
    container_name: checkpoint-s3-storage
    ports:
      - ${MINIO_SERVER_PORT}:9000
      - ${MINIO_DASHBOARD_PORT}:9001
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"

  rabbitmq:
    image: rabbitmq:management
    container_name: checkpoint-mq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - ${RABBITMQ_PORT_ONE}:5672
      - ${RABBITMQ_PORT_TWO}:15672
